env:
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb-base
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - import
rules:
  import/extensions: 0
  no-console: 0
